"use client"

import type React from "react"
import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ArrowLeft, FileText, Calendar, User, ExternalLink, Play, CheckCircle, History, Eye, Info } from "lucide-react"
import { TestScenarioScreen } from "@/components/test-scenario-screen"

interface SRSWorkspaceProps {
  srs: any
  onBack: () => void
}

export function SRSWorkspace({ srs, onBack }: SRSWorkspaceProps) {
  const [currentView, setCurrentView] = useState<"workspace" | "scenarios">("workspace")
  const [isGenerating, setIsGenerating] = useState(false)
  const [generationComplete, setGenerationComplete] = useState(false)
  const [generatedStats, setGeneratedStats] = useState({ scenarios: 0, testCases: 0 })
  const [showExportReport, setShowExportReport] = useState(false)

  const handleViewScenarios = () => {
    setCurrentView("scenarios")
  }

  const handleBackToWorkspace = () => {
    setCurrentView("workspace")
  }

  const handleGenerateTestCases = async () => {
    setIsGenerating(true)
    setGenerationComplete(false)

    await new Promise((resolve) => setTimeout(resolve, 2000))

    const scenarios = Math.floor(Math.random() * 5) + 2
    const testCases = Math.floor(Math.random() * 15) + 5

    setGeneratedStats({ scenarios, testCases })
    setIsGenerating(false)
    setGenerationComplete(true)
  }

  const handleExportReport = () => {
    setShowExportReport(true)
  }

  const generateReportData = () => {
    const totalTestCases = 13
    const successfulTestCases = 9
    const failedTestCases = 4
    const successRate = Math.round((successfulTestCases / totalTestCases) * 100)

    return {
      srsName: srs.name,
      totalScenarios: generationComplete ? generatedStats.scenarios : 3,
      totalTestCases,
      successfulTestCases,
      failedTestCases,
      successRate,
      generatedDate: new Date().toLocaleDateString(),
      testSteps: 45,
      executedSteps: 32,
      stepSuccessRate: Math.round((32 / 45) * 100),
    }
  }

  const downloadReport = () => {
    const reportData = generateReportData()
    const reportContent = `
SRS Test Report
===============

SRS Document: ${reportData.srsName}
Generated: ${reportData.generatedDate}

SUMMARY
-------
Total Scenarios: ${reportData.totalScenarios}
Total Test Cases: ${reportData.totalTestCases}
Successful Test Cases: ${reportData.successfulTestCases}
Failed Test Cases: ${reportData.failedTestCases}
Overall Success Rate: ${reportData.successRate}%

TEST STEPS
----------
Total Steps: ${reportData.testSteps}
Executed Steps: ${reportData.executedSteps}
Step Success Rate: ${reportData.stepSuccessRate}%

DETAILED BREAKDOWN
------------------
- Functional Tests: 8 cases (75% success rate)
- Integration Tests: 3 cases (67% success rate)
- UI Tests: 2 cases (100% success rate)

Generated by RPA4Web Testing Tool
    `.trim()

    const blob = new Blob([reportContent], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${srs.name.replace(/\s+/g, "_")}_Test_Report.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    setShowExportReport(false)
  }

  if (currentView === "scenarios") {
    return <TestScenarioScreen onBack={handleBackToWorkspace} srsId={srs.id} />
  }

  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b bg-card">
        <div className="flex h-16 items-center px-6">
          <Button variant="ghost" onClick={onBack} className="mr-4">
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to SRS List
          </Button>
          <h1 className="text-xl font-semibold">Workspace - {srs.name}</h1>
        </div>
      </nav>

      <div className="px-12 py-8">
        {generationComplete && (
          <div className="mb-8">
            <Card className="border-blue-200 bg-blue-50">
              <CardContent className="pt-6">
                <div className="flex items-center space-x-2 text-blue-800">
                  <CheckCircle className="h-4 w-4 text-blue-600" />
                  <span className="font-medium">
                    Test cases generated successfully! {generatedStats.scenarios} scenarios and{" "}
                    {generatedStats.testCases} test cases created.
                  </span>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        <div className="space-y-8">
          <Card className="mb-8">
            <CardHeader>
              <CardTitle className="flex items-center">
                <FileText className="h-5 w-5 mr-2" />
                {srs.name}
              </CardTitle>
              <CardDescription>{srs.description}</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">File Path</Label>
                  <p className="text-sm font-mono bg-muted p-2 rounded">{srs.filePath}</p>
                </div>
                <div>
                  <Label className="text-sm font-medium text-muted-foreground">Uploaded By</Label>
                  <div className="flex items-center space-x-2 mt-1">
                    <User className="h-4 w-4" />
                    <span className="text-sm">{srs.uploadedBy.username}</span>
                  </div>
                </div>
              </div>

              <div className="flex items-center justify-between">
                <div className="flex items-center space-x-2">
                  <Calendar className="h-4 w-4 text-muted-foreground" />
                  <span className="text-sm text-muted-foreground">
                    Last modified: {new Date().toLocaleDateString()}
                  </span>
                </div>
                <div className="flex items-center space-x-4">
                  <div className="flex items-center space-x-2">
                    <span className="text-sm text-muted-foreground">Processing:</span>
                    <Badge variant="secondary">Complete</Badge>
                  </div>
                  <div className="flex items-center space-x-2">
                    <span className="text-sm text-muted-foreground">Test Cases:</span>
                    <Badge>{generationComplete ? `${generatedStats.testCases} Generated` : "3 Generated"}</Badge>
                  </div>
                  <div className="flex items-center space-x-2">
                    <span className="text-sm text-muted-foreground">Scenarios:</span>
                    <Badge>{generationComplete ? `${generatedStats.scenarios} Active` : "1 Active"}</Badge>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card className="mb-8 border-blue-200 bg-blue-50/50">
            <CardHeader>
              <CardTitle className="flex items-center text-blue-800">
                <Info className="h-5 w-5 mr-2" />
                Guide
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-3 text-sm text-blue-700">
                <div className="flex items-start space-x-2">
                  <span className="font-medium">First time:</span>
                  <span>
                    When uploading an SRS for the first time, click "Generate Test Case" to create test scenarios and
                    cases automatically.
                  </span>
                </div>
                <div className="flex items-start space-x-2">
                  <span className="font-medium">Subsequent times:</span>
                  <span>
                    For existing SRS documents, go to "Test Scenario Management" to view, edit, and manage your test
                    scenarios.
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-3 lg:grid-cols-5 gap-6">
            <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={handleGenerateTestCases}>
              <CardContent className="p-6">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-green-100 rounded-lg">
                    <Play className="h-5 w-5 text-green-600" />
                  </div>
                  <h3 className="font-semibold">{isGenerating ? "Generating..." : "Generate Test Cases"}</h3>
                </div>
                <p className="text-sm text-muted-foreground">
                  {isGenerating ? "Creating test cases..." : "Automatically generate test cases from SRS"}
                </p>
              </CardContent>
            </Card>

            <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={handleViewScenarios}>
              <CardContent className="p-6">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-blue-100 rounded-lg">
                    <ExternalLink className="h-5 w-5 text-blue-600" />
                  </div>
                  <h3 className="font-semibold">Test Scenario Management</h3>
                </div>
                <p className="text-sm text-muted-foreground">Manage test scenarios for this SRS</p>
                
              </CardContent>
            </Card>

            <Card className="cursor-pointer hover:shadow-md transition-shadow">
              <CardContent className="p-6">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-gray-100 rounded-lg">
                    <Eye className="h-5 w-5 text-gray-600" />
                  </div>
                  <h3 className="font-semibold">View SRS Document</h3>
                </div>
                <p className="text-sm text-muted-foreground">View the original SRS document content</p>
              </CardContent>
            </Card>

            <Card className="cursor-pointer hover:shadow-md transition-shadow">
              <CardContent className="p-6">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-orange-100 rounded-lg">
                    <History className="h-5 w-5 text-orange-600" />
                  </div>
                  <h3 className="font-semibold">View History</h3>
                </div>
                <p className="text-sm text-muted-foreground">Review test execution history and changes</p>
              </CardContent>
            </Card>

            <Card className="cursor-pointer hover:shadow-md transition-shadow" onClick={handleExportReport}>
              <CardContent className="p-6">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-purple-100 rounded-lg">
                    <FileText className="h-5 w-5 text-purple-600" />
                  </div>
                  <h3 className="font-semibold">Export Report</h3>
                </div>
                <p className="text-sm text-muted-foreground">Generate comprehensive test execution report</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>

      {showExportReport && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <Card className="w-full max-w-2xl mx-4">
            <CardHeader>
              <CardTitle>Test Report - {srs.name}</CardTitle>
              <CardDescription>Comprehensive test case and execution summary</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              {(() => {
                const reportData = generateReportData()
                return (
                  <>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <h4 className="font-medium">Test Cases Overview</h4>
                        <div className="space-y-1 text-sm">
                          <div className="flex justify-between">
                            <span>Total Test Cases:</span>
                            <span className="font-medium">{reportData.totalTestCases}</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Successful:</span>
                            <span className="font-medium text-green-600">{reportData.successfulTestCases}</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Failed:</span>
                            <span className="font-medium text-red-600">{reportData.failedTestCases}</span>
                          </div>
                          <div className="flex justify-between border-t pt-1">
                            <span>Success Rate:</span>
                            <span className="font-medium">{reportData.successRate}%</span>
                          </div>
                        </div>
                      </div>

                      <div className="space-y-2">
                        <h4 className="font-medium">Test Steps Overview</h4>
                        <div className="space-y-1 text-sm">
                          <div className="flex justify-between">
                            <span>Total Steps:</span>
                            <span className="font-medium">{reportData.testSteps}</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Executed:</span>
                            <span className="font-medium text-blue-600">{reportData.executedSteps}</span>
                          </div>
                          <div className="flex justify-between">
                            <span>Pending:</span>
                            <span className="font-medium text-orange-600">
                              {reportData.testSteps - reportData.executedSteps}
                            </span>
                          </div>
                          <div className="flex justify-between border-t pt-1">
                            <span>Step Success Rate:</span>
                            <span className="font-medium">{reportData.stepSuccessRate}%</span>
                          </div>
                        </div>
                      </div>
                    </div>

                    <div className="space-y-2">
                      <h4 className="font-medium">Scenarios Summary</h4>
                      <div className="text-sm">
                        <div className="flex justify-between">
                          <span>Total Scenarios:</span>
                          <span className="font-medium">{reportData.totalScenarios}</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex justify-end space-x-2 pt-4 border-t">
                      <Button variant="outline" onClick={() => setShowExportReport(false)}>
                        Cancel
                      </Button>
                      <Button onClick={downloadReport}>
                        <FileText className="h-4 w-4 mr-2" />
                        Download Report
                      </Button>
                    </div>
                  </>
                )
              })()}
            </CardContent>
          </Card>
        </div>
      )}
    </div>
  )
}

function Label({ children, className }: { children: React.ReactNode; className?: string }) {
  return <div className={className}>{children}</div>
}
