export const mockUsers = [
  { id: 1, username: "admin", email: "admin@test.com", password: "admin123" },
  { id: 2, username: "tester1", email: "tester1@test.com", password: "password123" },
  { id: 3, username: "tester2", email: "tester2@test.com", password: "secret123" },
]

export const mockSRS = [
  {
    id: 1,
    name: "SRS Booking System",
    description: "Spec for the booking system",
    file_path: "/uploads/srs_booking.pdf",
    uploaded_by: 1,
  },
  {
    id: 2,
    name: "SRS E-commerce Platform",
    description: "Requirements for online shopping platform",
    file_path: "/uploads/srs_ecommerce.pdf",
    uploaded_by: 2,
  },
  {
    id: 3,
    name: "SRS Banking Portal",
    description: "Banking system requirements specification",
    file_path: "/uploads/srs_banking.pdf",
    uploaded_by: 1,
  },
  {
    id: 4,
    name: "SRS Healthcare Management",
    description: "Hospital management system requirements",
    file_path: "/uploads/srs_healthcare.pdf",
    uploaded_by: 3,
  },
  {
    id: 5,
    name: "SRS UI Management System",
    description: "User interface and component management system requirements",
    file_path: "/uploads/srs_ui_management.pdf",
    uploaded_by: 1,
  },
  {
    id: 6,
    name: "SRS Student Management System",
    description: "Academic institution student information management system requirements",
    file_path: "/uploads/srs_student_management.pdf",
    uploaded_by: 2,
  },
]

export const mockScenarios = [
  // Booking System scenarios
  {
    id: 1,
    srs_id: 1,
    title: "Successful Booking",
    web_url: "http://booking.example.com",
    description: "Test scenario for successful flight booking",
  },
  {
    id: 2,
    srs_id: 1,
    title: "Booking Cancellation",
    web_url: "http://booking.example.com",
    description: "Test scenario for canceling existing bookings",
  },
  {
    id: 3,
    srs_id: 1,
    title: "Payment Failure",
    web_url: "http://booking.example.com",
    description: "Test scenario for handling payment failures",
  },
  // E-commerce scenarios
  {
    id: 4,
    srs_id: 2,
    title: "Product Purchase",
    web_url: "http://shop.example.com",
    description: "Complete product purchase flow",
  },
  {
    id: 5,
    srs_id: 2,
    title: "Cart Management",
    web_url: "http://shop.example.com",
    description: "Add/remove items from shopping cart",
  },
  {
    id: 6,
    srs_id: 2,
    title: "User Registration",
    web_url: "http://shop.example.com",
    description: "New user account creation",
  },
  // Banking scenarios
  {
    id: 7,
    srs_id: 3,
    title: "Account Login",
    web_url: "http://bank.example.com",
    description: "Secure user authentication",
  },
  {
    id: 8,
    srs_id: 3,
    title: "Money Transfer",
    web_url: "http://bank.example.com",
    description: "Transfer funds between accounts",
  },
  {
    id: 9,
    srs_id: 3,
    title: "Transaction History",
    web_url: "http://bank.example.com",
    description: "View account transaction history",
  },
  // Healthcare scenarios
  {
    id: 10,
    srs_id: 4,
    title: "Patient Registration",
    web_url: "http://hospital.example.com",
    description: "Register new patient information",
  },
  {
    id: 11,
    srs_id: 4,
    title: "Appointment Booking",
    web_url: "http://hospital.example.com",
    description: "Schedule medical appointments",
  },
  // UI Management scenarios
  {
    id: 12,
    srs_id: 5,
    title: "Component Library Management",
    web_url: "http://ui.example.com",
    description: "Manage and organize UI components",
  },
  {
    id: 13,
    srs_id: 5,
    title: "Design System Updates",
    web_url: "http://ui.example.com",
    description: "Update design tokens and component styles",
  },
  {
    id: 14,
    srs_id: 5,
    title: "Theme Configuration",
    web_url: "http://ui.example.com",
    description: "Configure and apply different UI themes",
  },
  {
    id: 15,
    srs_id: 6,
    title: "Student Enrollment",
    web_url: "http://student.example.com",
    description: "Register new students and manage enrollment process",
  },
  {
    id: 16,
    srs_id: 6,
    title: "Grade Management",
    web_url: "http://student.example.com",
    description: "Record and manage student grades and transcripts",
  },
  {
    id: 17,
    srs_id: 6,
    title: "Course Registration",
    web_url: "http://student.example.com",
    description: "Allow students to register for courses and manage schedules",
  },
  {
    id: 18,
    srs_id: 6,
    title: "Fee Management",
    web_url: "http://student.example.com",
    description: "Handle tuition fees, payments, and financial records",
  },
]

export const mockTestCases = [
  // Booking System test cases
  {
    id: 1,
    scenario_id: 1,
    test_item: "One-way ticket booking",
    test_classification: "Functional",
    environment_condition: "Chrome on Windows 11",
    input_data_procedure: "Enter valid flight information",
    expected_output: "Booking confirmation is displayed",
  },
  {
    id: 2,
    scenario_id: 1,
    test_item: "Round-trip booking",
    test_classification: "Functional",
    environment_condition: "Firefox on macOS",
    input_data_procedure: "Select round-trip option with dates",
    expected_output: "Round-trip booking confirmed",
  },
  {
    id: 3,
    scenario_id: 2,
    test_item: "Cancel recent booking",
    test_classification: "Functional",
    environment_condition: "Chrome on Windows 11",
    input_data_procedure: "Navigate to bookings and cancel",
    expected_output: "Cancellation confirmation shown",
  },
  {
    id: 4,
    scenario_id: 3,
    test_item: "Invalid payment card",
    test_classification: "Negative",
    environment_condition: "Safari on macOS",
    input_data_procedure: "Enter expired credit card",
    expected_output: "Payment error message displayed",
  },
  // E-commerce test cases
  {
    id: 5,
    scenario_id: 4,
    test_item: "Buy single product",
    test_classification: "Functional",
    environment_condition: "Chrome on Windows 11",
    input_data_procedure: "Add product to cart and checkout",
    expected_output: "Order confirmation received",
  },
  {
    id: 6,
    scenario_id: 4,
    test_item: "Buy multiple products",
    test_classification: "Functional",
    environment_condition: "Edge on Windows 11",
    input_data_procedure: "Add multiple items and checkout",
    expected_output: "Bulk order confirmed",
  },
  {
    id: 7,
    scenario_id: 5,
    test_item: "Add items to cart",
    test_classification: "Functional",
    environment_condition: "Chrome on Android",
    input_data_procedure: "Browse and add various products",
    expected_output: "Cart updated with items",
  },
  {
    id: 8,
    scenario_id: 6,
    test_item: "Create new account",
    test_classification: "Functional",
    environment_condition: "Firefox on Linux",
    input_data_procedure: "Fill registration form",
    expected_output: "Account created successfully",
  },
  // Banking test cases
  {
    id: 9,
    scenario_id: 7,
    test_item: "Valid login credentials",
    test_classification: "Security",
    environment_condition: "Chrome on Windows 11",
    input_data_procedure: "Enter correct username/password",
    expected_output: "Dashboard access granted",
  },
  {
    id: 10,
    scenario_id: 8,
    test_item: "Transfer to savings",
    test_classification: "Functional",
    environment_condition: "Safari on iOS",
    input_data_procedure: "Transfer amount between accounts",
    expected_output: "Transfer completed successfully",
  },
  {
    id: 11,
    scenario_id: 9,
    test_item: "View last 30 days",
    test_classification: "Functional",
    environment_condition: "Chrome on macOS",
    input_data_procedure: "Select date range filter",
    expected_output: "Transaction list displayed",
  },
  // Healthcare test cases
  {
    id: 12,
    scenario_id: 10,
    test_item: "Register new patient",
    test_classification: "Functional",
    environment_condition: "Chrome on Windows 11",
    input_data_procedure: "Complete patient information form",
    expected_output: "Patient ID generated",
  },
  {
    id: 13,
    scenario_id: 11,
    test_item: "Book cardiology appointment",
    test_classification: "Functional",
    environment_condition: "Firefox on Windows 10",
    input_data_procedure: "Select doctor and available time slot",
    expected_output: "Appointment confirmed",
  },
  // UI Management test cases
  {
    id: 14,
    scenario_id: 12,
    test_item: "Create new component",
    test_classification: "Functional",
    environment_condition: "Chrome on macOS",
    input_data_procedure: "Use component builder to create button component",
    expected_output: "Component added to library with proper documentation",
  },
  {
    id: 15,
    scenario_id: 12,
    test_item: "Update existing component",
    test_classification: "Functional",
    environment_condition: "Firefox on Windows 11",
    input_data_procedure: "Modify component properties and styles",
    expected_output: "Component updated and version history maintained",
  },
  {
    id: 16,
    scenario_id: 13,
    test_item: "Apply design token changes",
    test_classification: "Integration",
    environment_condition: "Chrome on Linux",
    input_data_procedure: "Update color palette and typography tokens",
    expected_output: "All components reflect new design tokens",
  },
  {
    id: 17,
    scenario_id: 14,
    test_item: "Switch to dark theme",
    test_classification: "UI",
    environment_condition: "Safari on macOS",
    input_data_procedure: "Toggle theme switcher to dark mode",
    expected_output: "Interface switches to dark theme with proper contrast",
  },
  {
    id: 18,
    scenario_id: 15,
    test_item: "Enroll new student",
    test_classification: "Functional",
    environment_condition: "Chrome on Windows 11",
    input_data_procedure: "Complete student enrollment form with personal and academic information",
    expected_output: "Student ID generated and enrollment confirmation displayed",
  },
  {
    id: 19,
    scenario_id: 15,
    test_item: "Update student information",
    test_classification: "Functional",
    environment_condition: "Firefox on macOS",
    input_data_procedure: "Modify existing student contact and emergency information",
    expected_output: "Student record updated with change history maintained",
  },
  {
    id: 20,
    scenario_id: 16,
    test_item: "Enter semester grades",
    test_classification: "Functional",
    environment_condition: "Chrome on Linux",
    input_data_procedure: "Input grades for multiple students in a course",
    expected_output: "Grades saved and GPA calculations updated automatically",
  },
  {
    id: 21,
    scenario_id: 17,
    test_item: "Register for courses",
    test_classification: "Functional",
    environment_condition: "Edge on Windows 11",
    input_data_procedure: "Select courses from available catalog with prerequisite checking",
    expected_output: "Course registration confirmed with schedule conflicts resolved",
  },
  {
    id: 22,
    scenario_id: 18,
    test_item: "Process tuition payment",
    test_classification: "Financial",
    environment_condition: "Safari on iOS",
    input_data_procedure: "Make online tuition payment using credit card",
    expected_output: "Payment processed successfully with receipt generated",
  },
]

export const mockSteps = [
  // Test Case 1: One-way ticket booking
  {
    id: 1,
    test_case_id: 1,
    step_order: 1,
    action_description: "Open homepage",
    input_data: null,
    img_url: "/airline-booking-homepage.png",
    expected_page_url: "https://booking.example.com/home",
    script_code: 'driver.get("https://booking.example.com/home")',
  },
  {
    id: 2,
    test_case_id: 1,
    step_order: 2,
    action_description: "Select flight",
    input_data: "Choose Hanoi - Da Nang",
    img_url: "/flight-selection-page.png",
    expected_page_url: "https://booking.example.com/flights",
    script_code:
      'driver.find_element(By.ID, "departure").send_keys("Hanoi")\ndriver.find_element(By.ID, "destination").send_keys("Da Nang")\ndriver.find_element(By.ID, "search-btn").click()',
  },
  {
    id: 3,
    test_case_id: 1,
    step_order: 3,
    action_description: "Make payment",
    input_data: "Enter card information",
    img_url: "/payment-form.png",
    expected_page_url: "https://booking.example.com/payment",
    script_code:
      'driver.find_element(By.ID, "card-number").send_keys("4111111111111111")\ndriver.find_element(By.ID, "expiry").send_keys("12/25")\ndriver.find_element(By.ID, "cvv").send_keys("123")\ndriver.find_element(By.ID, "pay-btn").click()',
  },
  // Test Case 5: Buy single product
  {
    id: 4,
    test_case_id: 5,
    step_order: 1,
    action_description: "Browse products",
    input_data: null,
    img_url: "/ecommerce-product-catalog.png",
    expected_page_url: "https://shop.example.com/products",
    script_code: 'driver.get("https://shop.example.com/products")',
  },
  {
    id: 5,
    test_case_id: 5,
    step_order: 2,
    action_description: "Add to cart",
    input_data: "Select laptop product",
    img_url: "/product-detail-page-with-add-to-cart.png",
    expected_page_url: "https://shop.example.com/product/laptop-123",
    script_code:
      'driver.find_element(By.XPATH, "//div[@data-product=\'laptop\']").click()\ndriver.find_element(By.ID, "add-to-cart").click()',
  },
  {
    id: 6,
    test_case_id: 5,
    step_order: 3,
    action_description: "Proceed to checkout",
    input_data: null,
    img_url: "/shopping-cart-checkout.png",
    expected_page_url: "https://shop.example.com/checkout",
    script_code: 'driver.find_element(By.ID, "cart-icon").click()\ndriver.find_element(By.ID, "checkout-btn").click()',
  },
  {
    id: 7,
    test_case_id: 5,
    step_order: 4,
    action_description: "Complete payment",
    input_data: "Credit card details",
    img_url: "/payment-confirmation-page.png",
    expected_page_url: "https://shop.example.com/order-complete",
    script_code:
      'driver.find_element(By.ID, "payment-method").click()\ndriver.find_element(By.ID, "card-details").send_keys("4532123456789012")\ndriver.find_element(By.ID, "complete-order").click()',
  },
  // Test Case 9: Valid login credentials
  {
    id: 8,
    test_case_id: 9,
    step_order: 1,
    action_description: "Navigate to login",
    input_data: null,
    img_url: "/banking-login-page.png",
    expected_page_url: "https://bank.example.com/login",
    script_code: 'driver.get("https://bank.example.com/login")',
  },
  {
    id: 9,
    test_case_id: 9,
    step_order: 2,
    action_description: "Enter credentials",
    input_data: "Username: john.doe, Password: ****",
    img_url: "/login-form-filled.png",
    expected_page_url: "https://bank.example.com/login",
    script_code:
      'driver.find_element(By.ID, "username").send_keys("john.doe")\ndriver.find_element(By.ID, "password").send_keys("securepass123")\ndriver.find_element(By.ID, "login-btn").click()',
  },
  {
    id: 10,
    test_case_id: 9,
    step_order: 3,
    action_description: "Access dashboard",
    input_data: null,
    img_url: "/banking-dashboard-with-account-balance.png",
    expected_page_url: "https://bank.example.com/dashboard",
    script_code: 'WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "dashboard")))',
  },
  // Test Case 12: Register new patient
  {
    id: 11,
    test_case_id: 12,
    step_order: 1,
    action_description: "Open registration form",
    input_data: null,
    img_url: "/patient-registration-form.png",
    expected_page_url: "https://hospital.example.com/register",
    script_code: 'driver.get("https://hospital.example.com/register")',
  },
  {
    id: 12,
    test_case_id: 12,
    step_order: 2,
    action_description: "Fill patient details",
    input_data: "Name: Jane Smith, DOB: 1990-05-15",
    img_url: "/completed-patient-form.png",
    expected_page_url: "https://hospital.example.com/register",
    script_code:
      'driver.find_element(By.ID, "patient-name").send_keys("Jane Smith")\ndriver.find_element(By.ID, "dob").send_keys("1990-05-15")\ndriver.find_element(By.ID, "phone").send_keys("555-0123")',
  },
  {
    id: 13,
    test_case_id: 12,
    step_order: 3,
    action_description: "Submit registration",
    input_data: null,
    img_url: "/patient-registration-success.png",
    expected_page_url: "https://hospital.example.com/patient/12345",
    script_code:
      'driver.find_element(By.ID, "submit-registration").click()\nWebDriverWait(driver, 10).until(EC.url_contains("/patient/"))',
  },
  // Test Case 14: Create new component
  {
    id: 14,
    test_case_id: 14,
    step_order: 1,
    action_description: "Open component builder",
    input_data: null,
    img_url: "/ui-component-builder-dashboard.png",
    expected_page_url: "https://ui.example.com/builder",
    script_code: 'driver.get("https://ui.example.com/builder")',
  },
  {
    id: 15,
    test_case_id: 14,
    step_order: 2,
    action_description: "Select component type",
    input_data: "Choose Button component",
    img_url: "/component-type-selection.png",
    expected_page_url: "https://ui.example.com/builder/button",
    script_code: "driver.find_element(By.XPATH, \"//div[@data-component-type='button']\").click()",
  },
  {
    id: 16,
    test_case_id: 14,
    step_order: 3,
    action_description: "Configure component properties",
    input_data: "Set size, color, and variant options",
    img_url: "/component-properties-form.png",
    expected_page_url: "https://ui.example.com/builder/button/configure",
    script_code:
      'driver.find_element(By.ID, "component-name").send_keys("PrimaryButton")\ndriver.find_element(By.ID, "size-options").click()\ndriver.find_element(By.ID, "color-picker").click()',
  },
  {
    id: 17,
    test_case_id: 14,
    step_order: 4,
    action_description: "Save component to library",
    input_data: null,
    img_url: "/component-library-updated.png",
    expected_page_url: "https://ui.example.com/library",
    script_code:
      'driver.find_element(By.ID, "save-component").click()\nWebDriverWait(driver, 10).until(EC.url_contains("/library"))',
  },
  // Test Case 17: Switch to dark theme
  {
    id: 18,
    test_case_id: 17,
    step_order: 1,
    action_description: "Navigate to theme settings",
    input_data: null,
    img_url: "/theme-settings-page.png",
    expected_page_url: "https://ui.example.com/settings/themes",
    script_code: 'driver.get("https://ui.example.com/settings/themes")',
  },
  {
    id: 19,
    test_case_id: 17,
    step_order: 2,
    action_description: "Toggle dark theme",
    input_data: "Click dark theme toggle",
    img_url: "/dark-theme-toggle-active.png",
    expected_page_url: "https://ui.example.com/settings/themes",
    script_code: 'driver.find_element(By.ID, "dark-theme-toggle").click()\ntime.sleep(2)  // Wait for theme transition',
  },
  {
    id: 20,
    test_case_id: 17,
    step_order: 3,
    action_description: "Verify dark theme applied",
    input_data: null,
    img_url: "/ui-interface-dark-theme.png",
    expected_page_url: "https://ui.example.com/dashboard",
    script_code:
      'driver.get("https://ui.example.com/dashboard")\nassert "dark" in driver.find_element(By.TAG_NAME, "body").get_attribute("class")',
  },
  // Student Management steps
  {
    id: 21,
    test_case_id: 18,
    step_order: 1,
    action_description: "Open student enrollment form",
    input_data: null,
    img_url: "/student-enrollment-form.png",
    expected_page_url: "https://student.example.com/enroll",
    script_code: 'driver.get("https://student.example.com/enroll")',
  },
  {
    id: 22,
    test_case_id: 18,
    step_order: 2,
    action_description: "Fill student personal information",
    input_data: "Name: John Smith, DOB: 2000-03-15, Email: john.smith@email.com",
    img_url: "/student-personal-info-form.png",
    expected_page_url: "https://student.example.com/enroll",
    script_code:
      'driver.find_element(By.ID, "first-name").send_keys("John")\ndriver.find_element(By.ID, "last-name").send_keys("Smith")\ndriver.find_element(By.ID, "dob").send_keys("2000-03-15")\ndriver.find_element(By.ID, "email").send_keys("john.smith@email.com")',
  },
  {
    id: 23,
    test_case_id: 18,
    step_order: 3,
    action_description: "Submit enrollment application",
    input_data: null,
    img_url: "/student-enrollment-success.png",
    expected_page_url: "https://student.example.com/student/STU12345",
    script_code:
      'driver.find_element(By.ID, "submit-enrollment").click()\nWebDriverWait(driver, 10).until(EC.url_contains("/student/"))',
  },
  {
    id: 24,
    test_case_id: 20,
    step_order: 1,
    action_description: "Access grade entry system",
    input_data: null,
    img_url: "/grade-entry-dashboard.png",
    expected_page_url: "https://student.example.com/grades/entry",
    script_code: 'driver.get("https://student.example.com/grades/entry")',
  },
  {
    id: 25,
    test_case_id: 20,
    step_order: 2,
    action_description: "Select course and enter grades",
    input_data: "Course: CS101, Student grades: A, B+, A-, B",
    img_url: "/grade-entry-form-filled.png",
    expected_page_url: "https://student.example.com/grades/entry/CS101",
    script_code:
      'driver.find_element(By.ID, "course-select").click()\ndriver.find_element(By.XPATH, "//option[@value=\'CS101\']").click()\ndriver.find_element(By.XPATH, "//input[@data-student=\'1\']").send_keys("A")\ndriver.find_element(By.XPATH, "//input[@data-student=\'2\']").send_keys("B+")',
  },
  {
    id: 26,
    test_case_id: 20,
    step_order: 3,
    action_description: "Save grades and update GPA",
    input_data: null,
    img_url: "/grades-saved-confirmation.png",
    expected_page_url: "https://student.example.com/grades/summary",
    script_code:
      'driver.find_element(By.ID, "save-grades").click()\nWebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "gpa-updated")))',
  },
]

export const mockExpectedResults = [
  // Test Case 1 expected results
  {
    id: 1,
    test_case_id: 1,
    step_id: 1,
    description: "Homepage displays correctly with search form",
    verification_type: "Step",
  },
  {
    id: 2,
    test_case_id: 1,
    step_id: 2,
    description: "Flight list is displayed with available options",
    verification_type: "Step",
  },
  {
    id: 3,
    test_case_id: 1,
    step_id: 3,
    description: "Booking confirmation is shown with ticket details",
    verification_type: "Case",
  },

  // Test Case 5 expected results
  {
    id: 4,
    test_case_id: 5,
    step_id: 4,
    description: "Product catalog loads with filtering options",
    verification_type: "Step",
  },
  { id: 5, test_case_id: 5, step_id: 5, description: "Product added to cart successfully", verification_type: "Step" },
  { id: 6, test_case_id: 5, step_id: 6, description: "Checkout page displays cart items", verification_type: "Step" },
  {
    id: 7,
    test_case_id: 5,
    step_id: 7,
    description: "Order completed with confirmation number",
    verification_type: "Case",
  },

  // Test Case 9 expected results
  { id: 8, test_case_id: 9, step_id: 8, description: "Login page loads with secure form", verification_type: "Step" },
  { id: 9, test_case_id: 9, step_id: 9, description: "Credentials accepted without errors", verification_type: "Step" },
  {
    id: 10,
    test_case_id: 9,
    step_id: 10,
    description: "Dashboard shows account information",
    verification_type: "Case",
  },

  // Test Case 12 expected results
  {
    id: 11,
    test_case_id: 12,
    step_id: 11,
    description: "Patient ID generated and profile created",
    verification_type: "Case",
  },
  // Test Case 14 expected results
  {
    id: 12,
    test_case_id: 14,
    step_id: 12,
    description: "Component builder interface loads with available templates",
    verification_type: "Step",
  },
  {
    id: 13,
    test_case_id: 14,
    step_id: 13,
    description: "Button component type selected and configuration form appears",
    verification_type: "Step",
  },
  {
    id: 14,
    test_case_id: 14,
    step_id: 14,
    description: "Component properties configured with preview updating",
    verification_type: "Step",
  },
  {
    id: 15,
    test_case_id: 14,
    step_id: 15,
    description: "Component saved to library with documentation and code examples",
    verification_type: "Case",
  },
  // Test Case 17 expected results
  {
    id: 16,
    test_case_id: 17,
    step_id: 16,
    description: "Theme settings page displays with available theme options",
    verification_type: "Step",
  },
  {
    id: 17,
    test_case_id: 17,
    step_id: 17,
    description: "Dark theme toggle activated with visual feedback",
    verification_type: "Step",
  },
  {
    id: 18,
    test_case_id: 17,
    step_id: 18,
    description: "Interface successfully switches to dark theme with proper contrast",
    verification_type: "Case",
  },
]

export const mockConfigs = [
  {
    id: 1,
    browser: "Chrome",
    browser_version: "116.0",
    os: "Windows",
    os_version: "11",
    device: "Laptop",
    chrome_driver_path: "C:/drivers/chromedriver.exe",
    other_config: { headless: false },
  },
]

export const mockExecutions = [
  {
    id: 1,
    test_case_id: 1,
    config_id: 1,
    status: "Passed",
    execution_log: "Ran test case for successful booking",
    executed_by: 2,
  },
  {
    id: 2,
    test_case_id: 5,
    config_id: 1,
    status: "Passed",
    execution_log: "E-commerce purchase flow completed",
    executed_by: 1,
  },
  {
    id: 3,
    test_case_id: 9,
    config_id: 1,
    status: "Failed",
    execution_log: "Login failed due to timeout",
    executed_by: 3,
  },
  {
    id: 4,
    test_case_id: 12,
    config_id: 1,
    status: "Passed",
    execution_log: "Patient registration successful",
    executed_by: 2,
  },
]

export const mockExecutionSteps = [
  // Execution 1 steps (Booking)
  {
    id: 1,
    execution_id: 1,
    step_id: 1,
    status: "Passed",
    actual_output: "Homepage displayed with search form",
    screenshot_url: "/booking-homepage-screenshot.png",
    page_url: "https://booking.example.com/home",
  },
  {
    id: 2,
    execution_id: 1,
    step_id: 2,
    status: "Passed",
    actual_output: "Flight list displayed with 5 available flights",
    screenshot_url: "/flight-results-screenshot.png",
    page_url: "https://booking.example.com/flights",
  },
  {
    id: 3,
    execution_id: 1,
    step_id: 3,
    status: "Passed",
    actual_output: "Booking confirmation displayed with ticket #BK12345",
    screenshot_url: "/booking-confirmation-screenshot.png",
    page_url: "https://booking.example.com/confirmation",
  },

  // Execution 2 steps (E-commerce)
  {
    id: 4,
    execution_id: 2,
    step_id: 4,
    status: "Passed",
    actual_output: "Product catalog loaded with 50+ items",
    screenshot_url: "/product-catalog-screenshot.png",
    page_url: "https://shop.example.com/products",
  },
  {
    id: 5,
    execution_id: 2,
    step_id: 5,
    status: "Passed",
    actual_output: "Laptop added to cart, cart count updated to 1",
    screenshot_url: "/product-added-to-cart-screenshot.png",
    page_url: "https://shop.example.com/product/laptop-123",
  },
  {
    id: 6,
    execution_id: 2,
    step_id: 6,
    status: "Passed",
    actual_output: "Checkout page shows 1 item totaling $999",
    screenshot_url: "/placeholder.svg?height=400&width=600",
    page_url: "https://shop.example.com/checkout",
  },
  {
    id: 7,
    execution_id: 2,
    step_id: 7,
    status: "Passed",
    actual_output: "Order completed, confirmation #ORD67890",
    screenshot_url: "/placeholder.svg?height=400&width=600",
    page_url: "https://shop.example.com/order-complete",
  },

  // Execution 3 steps (Banking - Failed)
  {
    id: 8,
    execution_id: 3,
    step_id: 8,
    status: "Passed",
    actual_output: "Login page loaded successfully",
    screenshot_url: "/placeholder.svg?height=400&width=600",
    page_url: "https://bank.example.com/login",
  },
  {
    id: 9,
    execution_id: 3,
    step_id: 9,
    status: "Passed",
    actual_output: "Credentials entered, form submitted",
    screenshot_url: "/placeholder.svg?height=400&width=600",
    page_url: "https://bank.example.com/login",
  },
  {
    id: 10,
    execution_id: 3,
    step_id: 10,
    status: "Failed",
    actual_output: "Page timeout after 30 seconds",
    screenshot_url: "/placeholder.svg?height=400&width=600",
    page_url: "https://bank.example.com/login",
  },
]

export const mockVerifications = [
  // Execution 1 verifications
  { id: 1, execution_id: 1, execution_step_id: 1, expected_id: 1, status: "Matched", score: 0.95 },
  { id: 2, execution_id: 1, execution_step_id: 2, expected_id: 2, status: "Matched", score: 0.88 },
  { id: 3, execution_id: 1, execution_step_id: 3, expected_id: 3, status: "Matched", score: 0.92 },

  // Execution 2 verifications
  { id: 4, execution_id: 2, execution_step_id: 4, expected_id: 4, status: "Matched", score: 0.97 },
  { id: 5, execution_id: 2, execution_step_id: 5, expected_id: 5, status: "Matched", score: 1.0 },
  { id: 6, execution_id: 2, execution_step_id: 6, expected_id: 6, status: "Matched", score: 0.89 },
  { id: 7, execution_id: 2, execution_step_id: 7, expected_id: 7, status: "Matched", score: 0.94 },

  // Execution 3 verifications (with failure)
  { id: 8, execution_id: 3, execution_step_id: 8, expected_id: 8, status: "Matched", score: 1.0 },
  { id: 9, execution_id: 3, execution_step_id: 9, expected_id: 9, status: "Matched", score: 0.85 },
  { id: 10, execution_id: 3, execution_step_id: 10, expected_id: 10, status: "Not Matched", score: 0.0 },
]
